site_name: El Santuario Del Buen Gusto
repo_name: Documentacion El Santuario Del Buen Gusto
site_dir: public
docs_dir: ../docs
theme:
  language: ca
  name: material
  features:
    - navigation.instant
    - navigation.indexes
   # - navigation.sections
    - navigation.path
    - header.autohide
    - search.highlight
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
  favicon: images/Logo.jpeg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:                 
      permalink: true
plugins:
  - mkdocs-video
  - search:
      lang: 
        - es
        - en
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - with-pdf:
      cover_logo: images/enunciat/diagrama-xarxa.png
      cover_subtitle: Solució exercici
      two_columns_level: 3
      output_path: document.pdf
nav:

  - Documentacion:
      - Planificacion Spints: 
          - Sprint 1: Documentacion/PlanificacionSprint/Sprint1/Sprint1Index.md
          - Sprint 2: Documentacion/PlanificacionSprint/Sprint2/Sprint2Index.md
          - Sprint 3: Documentacion/PlanificacionSprint/Sprint3/Sprint3Index.md
          - Sprint1MongoDB: Documentacion/PlanificacionSprint/Sprint1MongoDB/Sprint1MongoDB.md

      - Base de Datos: Documentacion/BaseDeDatos/BaseDeDatosIndex.md
      - Java: Documentacion/Java/JavaIndex.md
      - Lenguaje de Marcas: Documentacion/LenguajeDeMarcas/LenguajeDeMarcasIndex.md
      - Entornos de Desarollo: Documentacion/EntornosDeDesarollo/EntornosDeDesarolloIndex.md
      - Sistemas Informaticos: Documentacion/SistemasInformaticos/SistemasInformaticosIndex.md
